# Generated by Django 3.1.7 on 2021-03-20 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms1app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSAuthorContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_title', models.CharField(max_length=30)),
                ('content_body', models.CharField(max_length=300)),
                ('content_summary', models.CharField(max_length=60)),
                ('content_file', models.FileField(upload_to='')),
                ('content_category', models.CharField(max_length=60)),
                ('cmsusers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms1app.cmsauthor')),
            ],
        ),
    ]
