# Generated by Django 2.2.2 on 2021-03-22 08:55

import content.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSAuthorContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_title', models.CharField(blank=True, max_length=30)),
                ('content_body', models.TextField(blank=True, max_length=300)),
                ('content_summary', models.TextField(blank=True, max_length=60)),
                ('content_file_pdf', models.FileField(blank=True, upload_to=content.models.upload_location)),
                ('content_category', models.CharField(blank=True, max_length=50)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
