# Generated by Django 3.1.7 on 2021-03-19 06:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CMSUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('user_password', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='The Password must have minimum length of 8 characters          1 UpperCase Letter and 1 Lowercase Letter', regex='^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)[a-zA-Z\\d]{8,}$')])),
                ('user_firstname', models.CharField(max_length=50)),
                ('user_lastname', models.CharField(max_length=50)),
                ('user_phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('user_address', models.TextField(blank=True, default='')),
                ('user_city', models.CharField(blank=True, default='', max_length=50)),
                ('user_state', models.CharField(blank=True, default='', max_length=50)),
                ('user_country', models.CharField(blank=True, default='', max_length=50)),
                ('user_pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Enter Valid Pincode', regex='^\\d{4}|\\d{6}')])),
                ('user_role', models.CharField(choices=[('Admin', 'admin'), ('Author', 'author')], default='Admin', max_length=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CMSUsersContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_title', models.CharField(max_length=30)),
                ('content_body', models.CharField(max_length=300)),
                ('content_summary', models.CharField(max_length=60)),
                ('content_file', models.FileField(upload_to='')),
                ('content_category', models.CharField(max_length=60)),
                ('cmsusers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
